config/routes.rb
Rails.application.routes.draw do
  get 'tickets/index'
	post '/', to: 'tickets#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/excavator.rb
class Excavator < ApplicationRecord
  belongs_to :ticket
end

app/models/ticket.rb
class Ticket < ApplicationRecord
	has_one :excavator
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :create

  def index
	  @ticket = Ticket.last
		@excavator = Excavator.last
  end
 
	def create
    @ticket = Ticket.new(
			request_number: params["RequestNumber"],
			sequence_number: Integer(params["SequenceNumber"]),
			request_type: params["RequestType"],
			response_due_date_time: DateTime.parse(params["DateTimes"]["ResponseDueDateTime"]),
			primary_service_area_code: params["ServiceArea"]["PrimaryServiceAreaCode"]["SACode"],
			additional_service_area_codes: params["ServiceArea"]["AdditionalServiceAreaCodes"]["SACode"],
			well_known_text: params["ExcavationInfo"]["DigsiteInfo"]["WellKnownText"],
			)
		@ticket.save

		@excavator = Excavator.new(
		  ticket_id: @ticket.id,
			company_name: params["Excavator"]["CompanyName"],
			crew_on_site: ActiveRecord::Type::Boolean.new.cast(params["Excavator"]["CrewOnSite"]),
			address: {address: params["Excavator"]["Address"],
			          city: params["Excavator"]["City"],
								state: params["Excavator"]["State"],
								zip: params["Excavator"]["Zip"]})
		@excavator.save
#render json: {status: 'SUCCESS', message: 'ok', data: @ticket}, status: :ok

# respond_to do |format|
#			   format.html
#			   format.json { redirect_to tickets_index_url}
#			 end
#		else
#		   render json: {status: 'ERROR', message: 'ok', data: @ticket.errors}, status: :ok
#		end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD384uPE1DUs9NIhqLpMR0qhCnh3UaIwkY&callback=initMap" async defer></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/_attribute.html.erb
<% unless attribute[0] =~ /(_?id\Z|_at\Z|well_known_text)/ %>
	<% text = "#{attribute[0].humanize} - "%>
  <% if attribute[1].is_a? Hash %>
		<% text += attribute[1].map {|k,v| " #{v}(#{k})"}.join(',')%>
	<% else %>
  	<% text += "#{attribute[1]}" %>
	<% end %>
	<li><%= text %></li>
<% end %>

app/views/tickets/create.html.erb
<h6>New Ticket successfully added</h6>
<%= link_to 'Render Ticket', tickets_index_path %>

app/views/tickets/index.html.erb
<h1>Ticket</h1>
<p id="polygon-text" hidden><%= @ticket.well_known_text.gsub(/(\w+\(\(|\)\))/, '')  %></p>
<ul>
  <%= render partial: "attribute", collection: @ticket.attributes %>
</ul>
</br>
<h3>Excavator data</h3>
<ul>
  <%= render partial: "attribute", collection: @excavator.attributes %>
</ul>
<div id="map"></div>